### PR TITLE
Update Motd.php

### PR DESCRIPTION
**Pull request by CrowBaldeYT**
idk why im makeing this Lmao

### CODE REVIEW

**Comment by callumrawlinson** [comment]
how is futurecraft going?

**Comment by CrowBaldeYT** [comment]
I have no money to buy a Server

**Comment by callumrawlinson** [comment]
really? so your looking for a job as a dev or server co owner? i need one

**Comment by callumrawlinson** [comment]
@CrowBaldeYT  i added you as a contributor on poggit
https://poggit.pmmp.io/p/MotdUI/1.0

**Comment by CrowBaldeYT** [comment]
yes, Send me your Server,
And i look that i can to be your Dev \ Co-Owner

**Comment by callumrawlinson** [comment]
206.221.176.133:25687 i cant join yet as im busy but here you go

**Comment by callumrawlinson** [comment]
@CrowBaldeYT please can you fix this https://github.com/callumrawlinson/MOTD-UI/pull/3/conflicts

**Pull request merged**
